### ISSUE TITLE
Remove resources from the library project

### ISSUE THREAD

**Issue by mramsden** [emilsjolander/sprinkles#16]
Is there any chance though that you could remove the [styles.xml](https://github.com/emilsjolander/sprinkles/blob/master/library/res/values/styles.xml) and the [app_name](https://github.com/emilsjolander/sprinkles/blob/master/library/res/values/strings.xml#L3) definition in strings.xml, as it is messing with the layout previews in Android Studio?

**Comment by emilsjolander** [comment]
yeah ofc, i had just forgotten to remove them :+1:
