### ISSUE TITLE
Why is the android:minSdkVersion="14"?

### ISSUE THREAD

**Issue by praneetloke** [emilsjolander/sprinkles#17]
Can you lower this to, say, 8? I can pull down the sources and modify it myself and do a local build but I'd like to avoid that, that is, if Sprinkles would even work at that level.

**Comment by emilsjolander** [comment]
well this is a typo actually, good catch! Sprinkles actually targets version 9, updating now

**Comment by emilsjolander** [comment]
version 10\* android 2.3

**Comment by emilsjolander** [comment]
that said. it should work fine with 2.2 as well but i don't feel that i have the time to actively support it and very few apps run this version as of now.

**Comment by emilsjolander** [comment]
fixed now and syncing to maven central!

**Comment by praneetloke** [comment]
I agree with your comment about 2.2. I am beginning to care less about 2.3 (level ~~8~~ 10) as well but it is still a good 24% according to [the Android Dashboard](http://developer.android.com/about/dashboards/index.html?utm_content=buffer07ca2&utm_source=buffer&utm_medium=twitter&utm_campaign=Buffer).

**Comment by emilsjolander** [comment]
2.3 is lvl 10 :)

**Comment by emilsjolander** [comment]
2.2 is 8

**Comment by praneetloke** [comment]
Ah yes. :+1:
