### ISSUE TITLE
minSdkVersion=10

### ISSUE THREAD

**Issue by josh-burton** [emilsjolander/sprinkles#32]
The readme says "Sprinkles actively supports version 2.3 of Android and above but it should work on older versions as well"

But the library has minSdkVersion=10 in the manifest. Is this a bug or is the minSdk 10?

**Comment by emilsjolander** [comment]
Well version 2.3.3 is api lvl 10, that said changing to minSdkVersion=9 should not be a problem

**Comment by josh-burton** [comment]
Ah sorry! Was not thinking straight yesterday!
