### ISSUE TITLE
ContentValues retrieved before beforeCreate is invoked

### ISSUE THREAD

**Issue by datadanne** [emilsjolander/sprinkles#39]
`Model.save` retrieves all `ContentValues` before invoking `beforeCreate()` which breaks fields that are not nullable but are initialized in `beforeCreate()`. An example of this can be seen in the sample where a Note cannot be saved because of a `NullPointerException` thrown by the `DateSerializer` for the field `createdAt`.

**Comment by datadanne** [comment]
The issue was introduced in f1d4fcc51d7b6f6e27e500b633db0901e76ec438.

**Comment by emilsjolander** [comment]
Good catch! I'll close this issue and we'll continue any conversations in the pull request issues by @zsiegel
