### ISSUE TITLE
How to add an Index?

### ISSUE THREAD

**Issue by jecelyin** [emilsjolander/sprinkles#43]
How to add an index to a table?

**Comment by emilsjolander** [comment]
This is something that has not yet been added. Should be easy enough to make this addition and i'll look into doing it this week :) Maybe an `@Index` annotation on the columns that should be indexed?

**Comment by emilsjolander** [comment]
Or perhaps a better solution is to add this as a kind of migration. This would also allow for removal of indexes

**Comment by emilsjolander** [comment]
@jecelyin I forgot to mention that this can already be done with `addRawStatement` in a `Migration`.
