### ISSUE TITLE
Is there a helper to do custom Delete/Update queries?

### ISSUE THREAD

**Issue by darko1002001** [emilsjolander/sprinkles#44]
I have a case where i need to delete all the rows that have a specific value for a column. Is this possible. i see that Query.one/Query.many does execute raw SQL statements but it is expecting a model as a result. These things need just a count of affected rows. 
Can you provide some more insight into this? How do you handle things like this?

**Comment by emilsjolander** [comment]
Currently the way to do it is to call `new SqlStatement("my raw sql string").execute(args ...)`. This will however not return the number of effected rows (A limitation that i would like to fix).
