### ISSUE TITLE
How do I get the results of Select count(*)..?

### ISSUE THREAD

**Issue by jecelyin** [emilsjolander/sprinkles#46]
How do I get the results of Select count(*) from table?

**Comment by emilsjolander** [comment]
You do this with the `@DynamicColumn` annotation. Here is a quick example:

```
class Result extends QueryResult {
    @DynamicColumn("my_count") int count;
}

Result result = Query.One(Result.class, "select count(*) as my_count from MyTable").get();
```

A working example of this can be found in the sample project. The `Note` class has a `tag_count` column which is of this form.
