### ISSUE TITLE
Push v1.2.1 to maven

### ISSUE THREAD

**Issue by jdreesen** [emilsjolander/sprinkles#47]
I just wanted to update to version 1.2.1 but gradle fails because it couldn't find `se.emilsjolander:sprinkles:1.2.1`.

**Comment by emilsjolander** [comment]
I had pushed the artefact but had forgotten to release it, thanks for the reminder! Should be up and running in the next couple of hours.

**Comment by jdreesen** [comment]
Great, thx :)
