### ISSUE TITLE
Use existing database

### ISSUE THREAD

**Issue by fstephany** [emilsjolander/sprinkles#48]
I would like to use Sprinkles with an existing database. Right now, the database name is hardcoded in `DbOpenHelper`. It would be great to be able to open a database with another name bundled in the App.

**Comment by emilsjolander** [comment]
Known limitation, it hasn't been a priority but i'll try to get it into the next version :+1:

**Comment by fstephany** [comment]
Great! I've forked the repo and will give it a try today.

**Comment by fstephany** [comment]
After a quick check, https://github.com/jgilfelt/android-sqlite-asset-helper does the trick quite nicely (but also subclass `SQLiteOpenHelper`). 

I don't know if this use case is important enough to bloat Sprinkles with this feature (either by replicating some pieces of the sqlite-asset-helper or by including it as a dependency).

**Comment by fstephany** [comment]
I've added a parameter to the Sprinkles init method: `Sprinkles init(Context context, SQLiteDatabase db)`. This init manually set the `sInstance` variable of the `DbOpenHelper` (hacky!). 
By doing so, sqlite-asset-helper handles the migration but I still can use Sprinkles for mapping my models. 

All in all, isn't it a bit weird that the DB instance is held by the DbOpenHelper? Maybe the static db variable should in Sprinkles? 

https://github.com/fstephany/sprinkles/commit/241139edb13e599d130d0ed2248a273cfdbd3da0

**Comment by emilsjolander** [comment]
This feels like a duplicate of pull request #49. ok if i close this and we keep the discussion there? Regarding the static variables, it's not pretty and i would like to change it, not decided how yet though.

**Comment by fstephany** [comment]
Ok, me can move the discussion in #49 ;)
