### ISSUE TITLE
Raw sql execution

### ISSUE THREAD

**Issue by emilsjolander** [emilsjolander/sprinkles#5]
Support for raw sql execution. Something a long the lines of `Sprinkles.exec(String sql, Object[] args)` and `Sprinkles.execAsync(String sql, Object[] args)`

**Comment by emilsjolander** [comment]
not really sure exactly how i want this api too look. I don't think this is very urgent so please comment if you feel you need this api!

**Comment by elihart** [comment]
This would be helpful to me for just getting specific fields without the overhead of creating all the model objects.

**Comment by emilsjolander** [comment]
This api was mostly thought as a way to support deleting or updating multiple rows as querying is already done by executing raw sql statements.

**Comment by fabriciomassula** [comment]
I really need raw query support.

Let me give You an example:
I have a table of 'transactions', that have a Double field named 'amount'.
I need to do a query of the sum of the amounts of some 'transactions'.
So the query will be "select sum(amount) from table WHERE ..."

I would like to get only one simple Double as response... I tryed to a custom QueryResult extending the QueryResult object, but without success. 

Thank You

**Comment by emilsjolander** [comment]
@fmdu A custom `QueryResult` is the answer to your problem! If that did not work then that is a bug or you are using it wrong (in which case the documentation should be updated) and i would love it if you posted that as a separate issue :+1:

**Comment by MariusVolkhart** [comment]
Big +1 for this. My use case comes from the testing side. I want to unit test my classes on the device, but can't add additional migrations. I'd like to create, delete and populate whatever tables I need during setup and teardown. Populating can be done, but create and delete I haven't figured out a good way using Sprinkles.

**Comment by jdreesen** [comment]
This would be nice, so +1

**Comment by emilsjolander** [comment]
I'm wrapping up the last couple of test and after that i will look into including this in the next release :+1:
