### ISSUE TITLE
Searching by Date

### ISSUE THREAD

**Issue by f2prateek** [emilsjolander/sprinkles#50]
Is sprinkles able to search by date?

Updating the sample app:

``` java
Query.many(Note.class,  "select Notes.*, " +
    "(select count(*) from NoteTagLinks where NoteTagLinks.note_id = Notes.id) as tag_count " +
    "from Notes where created_at = ?", new Date());
```

This never returns any entries.

**Comment by emilsjolander** [comment]
No, but this should definitely be added! Expect it to be possible in the next release ;)

**Comment by emilsjolander** [comment]
currently in master ;)

**Comment by f2prateek** [comment]
Awesome!

**Comment by f2prateek** [comment]
Will you be making snapshot releases? Trying to add submodules with gradle is kind of a pain

**Comment by emilsjolander** [comment]
I'm currently waiting for another issue to make a release, you could just install master to your local maven repo in the meantime

**Comment by f2prateek** [comment]
Hmm... './gradlew :library:install' fails. That would be the correct command right?

**Comment by emilsjolander** [comment]
Not sure tbh. I just made a release though so you should see the new version in maven central in the next couple of hours :+1:
