### ISSUE TITLE
What is the best way to delete all the data of a table?

### ISSUE THREAD

**Issue by tmsbn** [emilsjolander/sprinkles#62]
I have read the documentation but I am a little confused about how to clear the current date in the table. Currently I am doing this

ModelList<Person> person=ModelList.from(Query.all(Person.class).get())
person.deleteAll()

Is this the best way?

**Comment by emilsjolander** [comment]
Yes, this is the best way if you want att the callbacks to be called on Person.class

You could also perform the delete manually via `new SqlStatement("delete from Persons")`
