### ISSUE TITLE
Migrations - docs should make clear that execution order is important.

### ISSUE THREAD

**Issue by gdaniels** [emilsjolander/sprinkles#65]
Hey there - just checking out your neat little library.  Right now your migrations are controlled entirely by the size and order of the Sprinkles.mMigrations list, which is determined by the code that creates them.  Although your README makes clear that you shouldn't change a migration after it's in production, you should maybe also point out that you should a) never change the order of migrations in your code, and b) only add new migrations at the end?

**Comment by emilsjolander** [comment]
yeah, i'm reworking how migrations work and i will keep this in mind when writing the new documentation :+1:
