### ISSUE TITLE
Support CursorList writable?

### ISSUE THREAD

**Issue by yongjhih** [emilsjolander/sprinkles#66]
Nice to see this project,
8tory had also implemented CursorList for ActiveAndroid before known this project. I would like to share these repositories to you, hope helpful:
- https://github.com/8tory/NoTils (fork from novoda)
- https://github.com/8tory/ActiveAndroid (fork from pardom)

**Comment by emilsjolander** [comment]
What is the issue? Because a cursorlist is really just the result of a query so i don't know how much sense it makes to be able to write to this list. Could you give en example usage so i where and why you think this would be a useful addition? thanks!
