### ISSUE TITLE
Documentation describing functionality still not released

### ISSUE THREAD

**Issue by edu-zamora** [emilsjolander/sprinkles#71]
The current README describes the functionality in the last commits (as the new migration system) but there is no release containing these changes, which makes it impossible for users to use via gradle.

Should we still show the old documentation until the new version is ready to be released? Or are we ready to do a release with this?

**Comment by emilsjolander** [comment]
Well i was planing on doing the release much more quickly but have decided to go back and look at the design. I might rollback the latest commits and push back the old readme today. thanks for pointing it out :+1:

**Comment by emilsjolander** [comment]
I have reverted the changes and am working on a different branch with the other changes
