### ISSUE TITLE
Support for saveAsync passing in a transaction.

### ISSUE THREAD

**Issue by jordi-chacon** [emilsjolander/sprinkles#74]
Hi!

It would be very useful to have:

void saveAsync(Transaction t);
void saveAsync(Transaction t, OnSavedCallback callback);

Same goes for deletes.
Do you have any plans for implementing this?

Thanks and have a good day!

**Comment by emilsjolander** [comment]
How would you decide to commit or rollback a transaction in this case? Also, there is really nothing that promises the order in which the saves/deletes will happen which makes this api very hard to support. I suggest you use the synchronous methods and wrap those in an async task.

**Comment by jordi-chacon** [comment]
Thanks Emil, your suggestion is a great idea and that's exactly what I did. It works very well so thank you!
